# Generated by Django 4.2.5 on 2023-10-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, to='my_app_blog.topic'),
        ),
    ]
