# Generated by Django 4.2.6 on 2023-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.TextField()),
            ],
        ),
    ]
